# Generated by Django 4.0.3 on 2025-03-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_group_project_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
